name: red-discordbot-tmc
services:
  app:
    container_name: red-discordbot
    image: phasecorex/red-discordbot:full@sha256:6f90b2d6cb6d09a80071c4cd04e1d8311b5c9f2624c4545e225c8d5084eed995
    environment:
      - PREFIX=.
      - PUID=$PUID
      - PGID=$PGID
      - TOKEN=<your-discord-token>
      - TZ=$TZ
    volumes:
      - type: bind
        source: /DATA/AppData/TMC-Store/$AppID/data
        target: /data
    restart: unless-stopped
    privileged: false

x-casaos:
  icon: https://cdn.jsdelivr.net/gh/futuroatom/ZimaOS-Apps@gh-pages/apps/com.zimaos.red-discordbot/assets/icon.png
  index: /
  main: app
  port_map: ""
  scheme: http
  title:
    en_US: Red Discord Bot
  id: com.zimaos.red-discordbot
