name: 2fauth
services:
  2fauth:
    image: 2fauth/2fauth:5.4.3@sha256:d1089c1e4a1ee043346f2d2cbb2f4686471e2d81a9863977460b17db83d00899
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - target: 8000
        published: "8000"
        protocol: tcp
    restart: always
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID
        target: /2fauth
    container_name: 2fauth
x-casaos:
  main: 2fauth
  icon: https://cdn.jsdelivr.net/gh/futuroatom/ZimaOS-Apps@gh-pages/apps/com.zimaos.2fauth/assets/icon.png
  title:
    en_US: 2FAuth
  index: /
  port_map: "8000"
  id: com.zimaos.2fauth
