# https://github.com/IceWhaleTech/CasaOS-AppStore/blob/main/CONTRIBUTING.md

name: traefik-v2
services:
  traefik-v2:
    container_name: traefik-v2
    #command: --api.insecure=true --providers.docker
    command: >
      sh -c '
        if [ ! -f "/etc/traefik/traefik.yml" ]; then
          echo -n "No config file found. Downloading config from GitHub... "
          wget -O /etc/traefik/traefik.yml https://raw.githubusercontent.com/traefik/traefik/v2.10/traefik.sample.yml
          if [ $? -eq 0 ]; then
            echo "done."
          else
            echo "error."
            exit 1
          fi
          echo -n "Enabeling API... "
          sed -i "s/#api:/api:/" /etc/traefik/traefik.yml
          sed -i "s/#  insecure:/  insecure:/" /etc/traefik/traefik.yml
          echo "done."
          echo -n "Enabeling Docker... "
          sed -i "s/#providers:/providers:/g" /etc/traefik/traefik.yml
          sed -i "s/#  docker:/  docker:/g" /etc/traefik/traefik.yml
          sed -i "s/^#    endpoint: tcp:\/\/.*/    endpoint: \"unix:\/\/\/var\/run\/docker.sock\"/g"
      /etc/traefik/traefik.yml
          echo "done."
        fi
        traefik'
    image: traefik:v2.11@sha256:5ab6a40664576dab720e9a16934cbad9692b0d06d4cffee15c8c6c74f4d0c7cd
    network_mode: bridge
    ports:
      - target: 80
        published: "81"
        protocol: tcp
      - target: 443
        published: "443"
        protocol: tcp
      - target: 8080
        published: "8080"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /etc/traefik
x-casaos:
  icon: https://cdn.jsdelivr.net/gh/futuroatom/ZimaOS-Apps@gh-pages/apps/com.zimaos.traefik-v2/assets/icon.png
  index: /dashboard/
  main: traefik-v2
  port_map: "8080"
  title:
    en_US: Traefik v2
  id: com.zimaos.traefik-v2
