name: swingmusic
services:
  swingmusic:
    image: ghcr.io/swingmx/swingmusic@sha256:e6ccef307ebeadac967de0565b75e4906615ecfaac2a8f6bb82be13f111439d5
    container_name: swingmusic
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/Media/Music
        target: /music
    ports:
      - "1970:1970"
    restart: unless-stopped
x-casaos:
  main: swingmusic
  icon: https://cdn.jsdelivr.net/gh/futuroatom/ZimaOS-Apps@gh-pages/apps/com.zimaos.swingmusic/assets/icon.png
  title:
    en_US: Swing Music
    zh_CN: Swing Music
  index: /
  port_map: "1970"
  id: com.zimaos.swingmusic
