name: openspeedtest
services:
  openspeedtest:
    image: openspeedtest/latest:v2.0.5@sha256:12cb104a9c10ee2b3a9ffcc1992dfb72236e8c2e3a08aa700f19b705fe3f2f04
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - target: 3000
        published: "3004"
        protocol: tcp
    restart: always
    container_name: openspeedtest
x-casaos:
  main: openspeedtest
  icon: https://cdn.jsdelivr.net/gh/futuroatom/ZimaOS-Apps@gh-pages/apps/com.zimaos.openspeedtest/assets/icon.png
  title:
    en_US: OpenSpeedTest
  index: /
  port_map: "3004"
  id: com.zimaos.openspeedtest
