name: openspeedtest
services:
  openspeedtest:
    image: openspeedtest/latest:v2.0.5@sha256:ef2521c9471268449964e59c8e4dcbe70108988e0eae5e440800672b1f35ea05
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - target: 3000
        published: "3004"
        protocol: tcp
    restart: always
    container_name: openspeedtest
x-casaos:
  main: openspeedtest
  icon: https://cdn.jsdelivr.net/gh/futuroatom/ZimaOS-Apps@gh-pages/apps/com.zimaos.openspeedtest/assets/icon.png
  title:
    en_US: OpenSpeedTest
  index: /
  port_map: "3004"
  id: com.zimaos.openspeedtest
