name: anaconda3
services:
  anaconda3:
    container_name: anaconda3
    image: continuumio/anaconda3:2023.09-0@sha256:bf78b724e8eb028ed298fd46e757da5ed4e05184edf0ec6db2e24c8352491b71
    network_mode: bridge
    restart: unless-stopped
    environment:
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
      - PATH=/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    ports:
      - target: 8888
        published: "8888"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/notebooks
        target: /opt/notebooks
    command:
      - /bin/bash
      - "-c"
      - conda install -c conda-forge jupyterlab -y --quiet && jupyter lab --notebook-dir=/opt/notebooks --ip='*' --port=8888 --no-browser --allow-root
x-casaos:
  main: anaconda3
  icon: https://cdn.jsdelivr.net/gh/futuroatom/ZimaOS-Apps@gh-pages/apps/com.zimaos.anaconda3/assets/icon.png
  scheme: http
  port_map: "8888"
  index: /
  title:
    en_US: Anaconda3
  id: com.zimaos.anaconda3
