name: media-fetch-pro
services:
  media-fetch-pro:
    environment:
      PGID: $PGID
      PUID: $PUID
      TZ: $TZ
    image: correctroad/media-fetch-pro:0.3.2@sha256:dff6b366765ae03e23feabaa77b92c52eab95da20eac8b39e60898dc7ec0ced3
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - target: 7789
        published: "7789"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/Media/MediaFetchPro
        target: /var/opt/video
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /var/opt/config
    container_name: mediafetchpro
x-casaos:
  main: media-fetch-pro
  icon: https://cdn.jsdelivr.net/gh/futuroatom/ZimaOS-Apps@gh-pages/apps/com.zimaos.mediafetchpro/assets/icon.png
  title:
    en_US: Media Fetch Pro
  port_map: "7789"
  id: com.zimaos.mediafetchpro
